レイアウトの実装とtabler iconsのインストール
qin-team-recipe/14-frontend pull request #18
Opened 2023-06-28 11:54 UTC by shimizu-tomoya

実装が最後までできませんでしたので、途中経過になります。

2023-07-13 01:22 UTC, lightsound commented
LGTMです👍

2023-07-13 01:23 UTC, lightsound approved these changes

2023-07-17 10:54 UTC, lightsound requested changes
ご確認くださいませ〜

2023-07-17 10:54 UTC, lightsound commented on src/app/(top)/_components/menu.jsx
> +    id: "1",
こちら、idをわざわざ作る必要は無いですね。
一意の値であれば何でもいいので、例えばurlとかtextをkeyに用いた方が良いです。

2023-07-17 10:54 UTC, lightsound commented on src/app/(top)/_components/menu.jsx
> +const Navigations = [
変数は基本はcamelCaseが慣例ですね。なのでここは大文字じゃないほうが良いです。

2023-07-17 10:54 UTC, lightsound commented on src/app/(top)/_components/title.jsx
（意見が分かれるので）難しいところですが、コンポーネントのファイル名は大文字にすることは多いですね〜
体感、95%ぐらいの人はそうしてると思います。

2023-07-17 13:05 UTC, shimizu-tomoya commented on src/app/(top)/_components/menu.jsx
> +    id: "1",
4869f9e

URLは確実に一意の値になると思うので、idからURLに変更をしました。

2023-07-17 13:08 UTC, shimizu-tomoya commented on src/app/(top)/_components/menu.jsx
> +const Navigations = [
4b350c0

何も考えず大文字にしてしまいましたが、コンポーネント名と被り可読性に影響が出るなと思いました。

2023-07-17 13:10 UTC, shimizu-tomoya commented on src/app/(top)/_components/title.jsx
eb90ed7

コンポーネント名を変更しました。

2023-07-17 13:34 UTC, closed without merging